name: Action for saltoris

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        default: 'master' 
      tag:
        description: 'Tag to use'
        required: true

jobs:
  Deployment-to-saltoris:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Git
        run:   apt-get update &&   apt-get install -y git

      - name: Set Git user name and email
        run: |
          git config --global user.name "srihari62"
          git config --global user.email "srihari6281@gmail.com"

      - name: Change remote URL
        run: git remote set-url origin https://srihari62:${{secrets.PAT}}@github.com/srihari62/git-actions.git

      - name: Add changes to Git
        run: git add . 

      - name: Commit changes
        run: git commit -m "v.0.1" 

      - name: Push changes to origin
        run: git push -u origin master -f
        